version: "3.3"
services: 
  app: 
    restart: always
    build: .
    volumes: 
      - ./:/app
    tty: true
    ports:
      - "8587:3000"
    depends_on: ["mongo"]
  mongo:
    restart: always
    image: mongo:4
    ports:
      - "27017:27017"